---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/cf-cli
    tag: 'latest'

inputs:
- name: artifact
- name: ci

run:
  path: ci/ci/tasks/deploy.sh

params:
  CF_API: 
  CF_USERNAME: 
  CF_PASSWORD: 
  CF_ORG: 
  CF_SPACE:
  HOSTNAME:
  DOMAIN:
  NUM_INSTANCES:
  MEMORY: